version: '3.8'

volumes:
  postgres-data:
  mongo-data:

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 54321:5432

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017

  auth-service:
    build:
      context: ./auth-service
      target: development
    environment:
      PORT: 3000
      DB_PORT: 5432
      DB_HOST: postgres
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWD: ${POSTGRES_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB_USER}
      JWT_SECRET: ${AUTH_JWT_SERCRET}
    ports:
      - 3010:3000
    depends_on:
      - postgres

  account-service:
    build:
      context: ./account-service
      target: development
    environment:
      PORT: 3000
      DB_PORT: 27017
      DB_HOST: mongo
      DB_USER: ${MONGODB_DB_USER}
      DB_PASSWD: ${MONGODB_DB_PASSWORD}
      DB_NAME: account-service
    ports:
      - 3011:3000
    depends_on:
      - mongo
